"""add note_grades table

Revision ID: 1a36d88922ba
Revises: c1d2e3f4a5b6
Create Date: 2026-09-03 12:57:06.223889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a36d88922ba'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('points_forts', sa.JSON(), nullable=False),
    sa.Column('ameliorations', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id')
    )
    with op.batch_alter_table('note_grades', schema=None) as batch_op:
        batch_op.create_index('ix_note_grades_note_id', ['note_id'], unique=True)

    # NB : l'autogenerate detecte aussi des index GIN (*_search_idx) comme "manquants" sous
    # SQLite -- faux positif connu (skill deployment) : ces index existent deja en Postgres
    # (migration f5b331d38432), SQLite ne les voit simplement pas. Retires ici pour ne garder
    # que le vrai changement de schema (note_grades).
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_grades', schema=None) as batch_op:
        batch_op.drop_index('ix_note_grades_note_id')

    op.drop_table('note_grades')
    # ### end Alembic commands ###
