"""add public sharing fields

Revision ID: c23a7429e6f8
Revises: 06f0ddaea360
Create Date: 2026-06-09 22:28:23.433715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23a7429e6f8'
down_revision = '06f0ddaea360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('fork_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('original_author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_binders_original_author_id', 'users', ['original_author_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_share_token'), ['share_token'], unique=True)

    # Populate default values for existing rows
    op.execute("UPDATE binders SET is_public = False, fork_count = 0")
    op.execute("UPDATE notes SET is_public = False")

    # Alter columns to set nullable=False
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.alter_column('is_public', nullable=False, existing_type=sa.Boolean())
        batch_op.alter_column('fork_count', nullable=False, existing_type=sa.Integer())

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('is_public', nullable=False, existing_type=sa.Boolean())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_share_token'))
        batch_op.drop_column('share_token')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_author_id')
        batch_op.drop_column('fork_count')
        batch_op.drop_column('tags')
        batch_op.drop_column('description')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
