"""add last_blurting_at to notes

Revision ID: ccf1c1fc10a4
Revises: f4a8d9e2c731
Create Date: 2026-06-11 17:59:39.637370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ccf1c1fc10a4'
down_revision = 'f4a8d9e2c731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_blurting_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_share_token'))
        batch_op.drop_column('last_blurting_at')

    with op.batch_alter_table('binders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
